name: Cypress Tests

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL'
        required: false
        type: string
      tag:
        description: 'tag'
        required: false
        type: string
      env:
        description: 'env'
        required: false
        type: string

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
    
      - name: Test inputs
        run: |
          echo "URL: ${{ inputs.url }}"
          echo "TAG: ${{ inputs.tag }}"
          echo "env: ${{ inputs.env }}"

      - name: Cypress run
        uses: cypress-io/github-action@v4 # use the explicit version number
        with:
          start: npm run test
          browser: chrome
